services:
  - type: web
    name: crystal-grimoire-backend
    env: python
    repo: https://github.com/Domusgpt/crystal-grimoire-clean
    rootDir: backend_crystal
    buildCommand: pip install -r requirements.txt
    startCommand: python app_server.py
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 8000
      - key: HOST
        value: "0.0.0.0"