services:
  - type: web
    name: crystal-grimoire-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app_server.py"
    plan: free
    healthCheckPath: "/health"
    envVars:
      - key: PORT
        value: 8000
      - key: HOST
        value: "0.0.0.0"